sudo: required
services:
    - docker

script:
    - docker build -t sandhyay/node .
    - docker images sandhyay/node

before_deploy:
    - docker login -u sandhyay --password-stdin Sandy123$

deploy:
    provider: script
    script: docker push sandhyay/node
    on:
        branch: master