sudo: required
services:
    - docker

script:
    - docker build -t mannydesigns/node .
    - docker images mannydesigns/node

before_deploy:
    - docker login -u sandhya.yapuram@gmail.com -p Sandy123$

deploy:
    provider: script
    script: docker push mannydesigns/node
    on:
        branch: master